export const APP_CONFIG = {
  CHECKOUT_FABRICA_URL: "",
  CHECKOUT_BLUEPRINT_URL: "",
  CHECKOUT_PREMIUM_URL: "",
  SUPORTE_EMAIL: "",
  GPT_AGENT_URL: "",
  DEMO_ACCESS_PASSWORD: "fabrica-apps-ia",
  COMPANY_NAME: "NOME DA EMPRESA",
  COMPANY_DOCUMENT: "CNPJ A DEFINIR",
  RESPONSIBLE_NAME: "RESPONSÁVEL A DEFINIR",
};
