export const APP_CONFIG = {
  CHECKOUT_FABRICA_URL: "",
  CHECKOUT_BLUEPRINT_URL: "",
  CHECKOUT_PREMIUM_URL: "",
  SUPORTE_EMAIL: "",
  GPT_AGENT_URL: "https://chatgpt.com/g/g-6a331f876adc8191a174b85fa0aac1bf-arquiteto-de-aplicativos",
  DEMO_ACCESS_PASSWORD: "fabrica-apps-ia",
  COMPANY_NAME: "NOME DA EMPRESA",
  COMPANY_DOCUMENT: "CNPJ A DEFINIR",
  RESPONSIBLE_NAME: "RESPONSÁVEL A DEFINIR",
  SHOW_ANNOUNCEMENT_BAR: true,
  ANNOUNCEMENT_TEXT: "⚡ Oferta de lançamento ativa — De R$97 por apenas R$47 · Acesso imediato",
  ANNOUNCEMENT_CTA_TEXT: "Quero acessar →",
  ANNOUNCEMENT_CTA_LINK: "/checkout?plano=fabrica",
};
